# Use the official Node.js image with version 18
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port
EXPOSE 3000

# Generate Prisma Client and apply migrations
RUN npx prisma generate

# Command to run the application
CMD ["npm", "run", "start:dev"]
